spring:
  application:
    name: audition-api
  config:
    import: "optional:configserver:"
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mvc:
    throw-exception-if-no-handler-found: true
  sleuth:
    sampler:
      probability: 1.0
server:
  max-http-request-header-size: 16KB
  port: 8081
management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
    endpoint: "localhost:4317"
  endpoints:
    web:
      exposure:
        include: 'info,health' #DONE enable only info and health for security purposes. Consider that we may want to still access other actuator endpoints securely.
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"